import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0058bc",
        "primary-container": "#0070eb",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        "on-primary-container": "#fefcff",
        "secondary": "#5f5e60",
        "secondary-container": "#e2dfe1",
        "secondary-fixed": "#e4e2e4",
        "secondary-fixed-dim": "#c8c6c8",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1b1b1d",
        "on-secondary-fixed-variant": "#474649",
        "on-secondary-container": "#636264",
        "tertiary": "#5b5c60",
        "tertiary-container": "#747479",
        "tertiary-fixed": "#e3e2e7",
        "tertiary-fixed-dim": "#c7c6cb",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1a1b1f",
        "on-tertiary-fixed-variant": "#46464b",
        "on-tertiary-container": "#fefcff",
        "surface": "#fcf8fb",
        "surface-dim": "#dcd9dc",
        "surface-bright": "#fcf8fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f5",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7ea",
        "surface-container-highest": "#e4e2e4",
        "surface-variant": "#e4e2e4",
        "surface-tint": "#005bc1",
        "on-surface": "#1b1b1d",
        "on-surface-variant": "#414755",
        "on-background": "#1b1b1d",
        "background": "#fcf8fb",
        "inverse-surface": "#303032",
        "inverse-on-surface": "#f3f0f2",
        "inverse-primary": "#adc6ff",
        "outline": "#717786",
        "outline-variant": "#c1c6d7",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
